appirio-tech/direct-app

build.xml

@ykohata 
Do these values make sense to you based on what you know about TC Direct?

Set java source and target version in build.xml

---

build.xml

Made some changes build process inside the release branch. Update dev with thee changes.

Update dev with latest from technology-2015-07-23

---

README.md

the VM setup scripts already include these steps.

remove useless instructions

---

src/web/scripts/ckeditor/ckeditor/config.js

@ajefts I simplify it, please let me know if you need to remove more or adjust the layout

Simplify CKEditor toolbar

---

components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/UploadExternalServices.java
components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/UploadServices.java
components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/impl/DefaultUploadExternalServices.java
components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/impl/DefaultUploadServices.java
components/project_management/src/java/main/com/topcoder/management/project/ProjectPropertyType.java
components/resource_management/src/java/main/com/topcoder/management/resource/ResourceRole.java
services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/css/direct/launchcontest.css
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/main.js

Database needs to be updated.
```
database tcs_catalog;
INSERT INTO project_info_type_lu(project_info_type_id, name, description, create_user, create_date, modify_user, modify_date) VALUES (82, 'Private Project Status', 'Private Project Status', 'System', current, 'System', current);
INSERT INTO project_info_type_lu(project_info_type_id, name, description, create_user, create_date, modify_user, modify_date) VALUES (83, 'PreRegister Users', 'PreRegister Users', 'System', current, 'System', current);
```
and the Deployment Guide for reference
[Deployment Guide.docx](https://github.com/appirio-tech/direct-app/files/578314/Deployment.Guide.docx)

Support pre-register members for private challenges

---

src/web/WEB-INF/copilot-contests-details.jsp
src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/WEB-INF/post-a-copilot.jsp
src/web/scripts/copilots.js
src/web/scripts/launch/main.js
src/web/scripts/launchCopilotContest.js

Reverts appirio-tech/direct-app#160

Revert "Remove cmc task"

---

components/resource_management/src/java/main/com/topcoder/management/resource/Notification.java
components/resource_management/src/java/main/com/topcoder/management/resource/NotificationType.java
components/resource_management/src/java/main/com/topcoder/management/resource/ResourceRole.java
services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

this was having adverse effects when saving normal challenges...specifically during checkpoint saves

fixes for resource management related to tasks

---

src/java/main/com/topcoder/direct/services/view/action/ServiceBackendDataTablesAction.java
src/java/main/com/topcoder/direct/services/view/action/my/MyChallengesAction.java
src/java/main/com/topcoder/direct/services/view/action/my/MyCreatedChallengesAction.java

fix struts param issue

---

src/web/WEB-INF/includes/right.jsp

fix start new project link

---

services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/main.js

be able to lower prize for task and set actual start/end time for regisration phase

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java
src/web/scripts/launch/contestDetailSoftware.js

enable assigning members for active task and fix double payments issues

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java
services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java

fix phase date validation while closing challenge

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

fix reviewer/iterative reviewer should be removed while closing challenge

fix reviewer/iterative reviewer should be removed while closing.

---

src/java/main/com/topcoder/direct/services/view/action/contest/launch/SaveDraftContestAction.java

allow zero prize

---

services/project_service/src/java/main/com/topcoder/service/project/impl/ProjectServiceBean.java
src/web/scripts/common.js

allow any characters

---

services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java

adjust registration phase end date for design challenge

---

services/client_project_entities_dao/src/java/main/com/topcoder/clients/dao/ejb3/ProjectDAOBean.java

consider status for billing account

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

fix wrong call to updateSoftwareContest

---

src/web/WEB-INF/contest-details2.jsp
src/web/WEB-INF/editCockpitProject.jsp
src/web/WEB-INF/includes/jq_1_11_1.jsp
src/web/WEB-INF/includes/project/edit/editProjectPageModals.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/css/direct/editProject.css
src/web/scripts/editCockpitProject.js
src/web/scripts/launch/entity.js
src/web/scripts/launch/main.js

Reverts appirio-tech/direct-app#298

Revert "move project permission and notification input to use magicsuggest"

---

build.xml
circle.yml
src/java/main/com/topcoder/direct/services/view/action/contest/launch/CommonAction.java
src/java/main/com/topcoder/direct/services/view/ajax/SoftwareCompetitionBeanProcessor.java
src/web/WEB-INF/contest-details2.jsp
src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/jq_1_11_1.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/WEB-INF/includes/launch/orderReviewSoftware.jsp
src/web/WEB-INF/includes/launch/overviewSoftware.jsp
src/web/WEB-INF/includes/launch/reviewSoftware.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/css/direct/launchcontest.css
src/web/css/direct/magicsuggest.css
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/entity.js
src/web/scripts/launch/main.js
src/web/scripts/launch/pages/overview.js
token.properties.docker
token.properties.example
topcoder_global.properties.docker

Reverts appirio-tech/direct-app#300

Revert "Revert "magic suggest integration and misc bug fixes""

---

src/web/WEB-INF/contest-details2.jsp
src/web/WEB-INF/editCockpitProject.jsp
src/web/WEB-INF/includes/jq_1_11_1.jsp
src/web/WEB-INF/includes/project/edit/editProjectPageModals.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/css/direct/editProject.css
src/web/scripts/editCockpitProject.js
src/web/scripts/launch/entity.js
src/web/scripts/launch/main.js

Reverts appirio-tech/direct-app#299

Revert "Revert "move project permission and notification input to use magicsuggest""

---

src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/entity.js
src/web/scripts/launch/main.js

tcs_catalog:project_info_type_lu
INSERT INTO "informix".project_info_type_lu VALUES (84, 'Environment', 'Environment', 'SYSTEM', CURRENT, 'SYSTEM', CURRENT);
INSERT INTO "informix".project_info_type_lu VALUES (85, 'Code Repo', 'Code Repo', 'SYSTEM', CURRENT, 'SYSTEM', CURRENT);

add field: environment and code repo to project_info

---

src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/overview.jsp
src/web/WEB-INF/includes/launch/overviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/overviewSoftware.jsp
src/web/WEB-INF/includes/launch/review.jsp
src/web/WEB-INF/includes/launch/reviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/reviewSoftware.jsp
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/pages/overview.js
src/web/scripts/launch/pages/selection.js

For studio will not add entry Environment and Code Repo on project_info. For MM: html related related currently comment out, although will still create entry on project_info

remove env and repo on studio

---

src/java/main/com/topcoder/direct/services/view/action/project/CurrentProjectGamePlanAction.java

fix project gantt chart

---

services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java

enable post mortem phase for Code challenge

---

components/project_management/src/java/main/com/topcoder/management/project/ProjectPropertyType.java
services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java

#384 
issue: reviewer number for code with review type: internal will be changed to 2 while updating

fix reviewType internal for code while updating

---

src/java/main/com/topcoder/direct/services/view/util/DirectUtils.java

use batch query for getting user handle

---

build.xml

force override jq_1_11_1.jsp with the tokenized version

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java
src/java/main/com/topcoder/direct/services/view/action/contest/launch/CommonAction.java
src/java/main/com/topcoder/direct/services/view/action/contest/launch/GetContestAction.java

Fix null pointer exception

---

src/web/WEB-INF/contest-details2.jsp
src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/footer.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launchcontest.js

add ToolTip on estimate effort hours

---

services/client_project_entities_dao/src/java/main/com/topcoder/clients/model/Client.java
src/java/main/com/topcoder/direct/services/view/action/contest/launch/CommonAction.java
src/java/main/com/topcoder/direct/services/view/action/contest/launch/GetContestAction.java

enable null value for Client effortHours

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

NPE on ConstestServiceFacadeBean.getSoftwareContestByProjectId effortrtHoursEnabled

---

components/project_management/src/java/main/com/topcoder/management/project/ProjectPropertyType.java
services/client_project_entities_dao/src/java/main/com/topcoder/clients/dao/ejb3/ProjectDAOBean.java
services/client_project_entities_dao/src/java/main/com/topcoder/clients/model/Client.java
services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java
services/project_services/src/java/main/com/topcoder/project/service/impl/ProjectServicesImpl.java
services/specification_review_service/test_files/insert.sql
src/java/main/com/topcoder/direct/services/view/action/contest/launch/CommonAction.java
src/java/main/com/topcoder/direct/services/view/action/contest/launch/GetContestAction.java
src/web/WEB-INF/contest-details2.jsp
src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/WEB-INF/includes/launch/orderReview.jsp
src/web/WEB-INF/includes/launch/orderReviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/orderReviewSoftware.jsp
src/web/WEB-INF/includes/launch/review.jsp
src/web/WEB-INF/includes/launch/reviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/reviewSoftware.jsp
src/web/WEB-INF/launch-contest.jsp
src/web/css/direct/launchcontest.css
src/web/scripts/launch/contestDetail.js
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/main.js
src/web/scripts/launch/pages/orderReview.js
src/web/scripts/launch/pages/review.js
src/web/scripts/launch/pages/selection.js
src/web/scripts/launchcontest.js

@skyhit could we have someone test this and redeploy?  We are moving effort hours to effort days.  It is a text change and some variable changes.  I will update the DB.

switched from hours to days

---

src/java/main/com/topcoder/direct/services/view/action/project/edit/SaveCockpitProjectSettingAction.java

* fix for adding member to direct project problem

fix for adding member to direct project problem (#448)

---

src/web/WEB-INF/includes/contest/editTab.jsp
src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/contestSelection.jsp
src/web/WEB-INF/includes/launch/orderReview.jsp
src/web/WEB-INF/includes/launch/orderReviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/orderReviewSoftware.jsp
src/web/WEB-INF/includes/launch/review.jsp
src/web/WEB-INF/includes/launch/reviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/reviewSoftware.jsp
src/web/css/direct/launchcontest.css
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/entity.js
src/web/scripts/launch/main.js
src/web/scripts/launch/pages/orderReview.js
src/web/scripts/launch/pages/review.js
src/web/scripts/launch/pages/selection.js
src/web/scripts/launchcontest.js

tcs_catalog
```sql
INSERT INTO informix.project_info_type_lu
(project_info_type_id, name, description, create_user, create_date, modify_user, modify_date)
VALUES(89, 'Estimate Efforts Days Offshore', 'Estimate Efforts Days Offshore', 'System', CURRENT, 'System', CURRENT);
INSERT INTO informix.project_info_type_lu
(project_info_type_id, name, description, create_user, create_date, modify_user, modify_date)
VALUES(90, 'Estimate Efforts Days Onsite', 'Estimate Efforts Days Onsite', 'System', CURRENT, 'System', CURRENT);
```
for #469

Add Effort Estimates Offshore/Onsite fields

---

src/web/WEB-INF/includes/contest/editTabMarathon.jsp
src/web/WEB-INF/includes/contest/editTabSoftware.jsp
src/web/WEB-INF/includes/launch/overviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/overviewSoftware.jsp
src/web/WEB-INF/includes/launch/reviewAlgorithm.jsp
src/web/WEB-INF/includes/launch/reviewSoftware.jsp
src/web/css/direct/launchcontest.css
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/main.js
src/web/scripts/launch/pages/overview.js

Add technology and platform to Marathon Match

---

conf/Direct.properties
src/java/main/com/topcoder/direct/services/view/action/contest/launch/SaveDraftContestAction.java
src/java/main/com/topcoder/direct/services/view/ajax/SoftwareCompetitionBeanProcessor.java
src/java/main/com/topcoder/direct/services/view/util/DirectProperties.java
src/web/WEB-INF/includes/jq_1_11_1.jsp
src/web/scripts/launch/contestDetailSoftware.js
src/web/scripts/launch/main.js
src/web/scripts/launch/pages/selection.js
src/web/scripts/launchcontest.js
token.properties.docker
token.properties.example

#516 
new `token.properties` entries:
```
@trialBillingId@ =
@defaultGroupIdForTrial@ =
```

Add default groups for trial

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

Fix "Private task Closure in Direct should populate actual start and end time"
https://topcoder.atlassian.net/browse/SET-3
1. Open https://www.topcoder-dev.com/direct/launch/home
2. Create a private task with the following parameters:
2.1 - Challenge Type: First2Finish
2.2 - Check the "Task" checkbox to make it private task
2.3 - Assign the task to a member (Could not do this step in direct in dev environment, used Online Review for it)
2.4 - Set the start date in the future
2.5 - Follow the challenge creation wizard to the end to launch the challenge.
3. Once the challenge is launched, Go to the contest details page in direct.
For example: https://www.topcoder-dev.com/direct/contest/detail?projectId=30056507
4. In the contest details page, close the private task and choose a winner by …

Fix private task closure registration start/end date population issue

---

conf/ApplicationServer.properties
src/java/main/com/topcoder/direct/services/configs/ServerConfiguration.java
src/web/WEB-INF/includes/newHeader.jsp
src/web/WEB-INF/includes/right.jsp
token.properties.docker
token.properties.example

All new projects creation operations are redirected to Topcoder Connect.
The target connect URL is configured in token.properties - configuration parameter `@TopcoderConnectUrl@`
Default value https://connect.topcoder.com is used

Redirect project creation to Topcoder Connect

---

.circleci/config.yml
components/project_management/src/java/main/com/topcoder/management/project/ProjectGroup.java

Potential fix of https://github.com/appirio-tech/direct-app/issues/537

Fixing serialization issue with ProjectGroup

---

src/web/WEB-INF/includes/footerScripts.jsp

Update the default NDA variable to use the latest NDA - 21374 (Replacing 21343)

Update Default NDA on Direct to v3 - 21374

---

services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java

As explained in https://github.com/appirio-tech/direct-app/issues/551
`skipForum` flag is added
NOTE: It's not tested!

#551 allow skipForum in ContestServiceFacadeBean.createSoftwareContest
